### ISSUE TITLE
Project logo has a large border

### ISSUE THREAD

**Issue by siko1056** [gnu-octave/pkg-jupyter-notebook#3]
Was it possible to remove the invisible border from the logo?  This causes the icon to be displayed quite small on Octave packages: <https://gnu-octave.github.io/packages/>.

**Comment by Abdallah-Elshamy** [comment]
I cropped it in 8f9cf1d0e2f3be97a7da65964e45d424464d8599

**Comment by siko1056** [comment]
Thank you @Abdallah-Elshamy :+1:
